### ISSUE TITLE
Image Overflow

### ISSUE THREAD

**Issue by Thicccy** [sussysoft/Sussymoji#16]
- Images with a height > width ratio overflow vertically over the other elements in the ImagePopup
- Images with height < width ratio seem to fit fine no matter the size

**Comment by ctrlcam** [comment]
This was fixed in latest commit. Scrollbar now appears when necessary.

![image](https://github.com/sussysoft/Sussymoji/assets/59180245/30f14f47-9d76-43a0-ac95-665932eb3c7d)
